# Site settings
title: Hackstub
description: "Un hackerspace Ã  Strasbourg"
baseurl: ""
url: "http://hackstub.netlib.re"
github_username:  hackstub

# Build settings
markdown: kramdown
permalink: pretty
